import type { NextPage } from 'next'
import Head from 'next/head'

import Topbar from './topbar'

const Layout: NextPage = ({ children }) => {
  return (
    <div>
      <Head>
        <title>{process.env.test}</title>

        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
        {/* <link rel="icon" sizes="192x192" href="/favicon.png" /> */}

        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* Chrome, Firefox and Opera */}
        {/* will not be used in android device when the dark mode is enabled. */}
        <meta name="theme-color" content="#FF4F4F" />
        {/* Windows Phone */}
        <meta name="msapplication-navbutton-color" content="#FF4F4F" />
        {/* iOS Safari */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="#black-translucent" />
      </Head>

      <Topbar />

      <main>
        {children}
      </main>

      <footer className="footer">
        Copyright (c) 2021, Jisu Sim. All rights reserved.
      </footer>

      <style jsx>{`
        .footer {
          font-family: 'Consolas', 'Ubuntu Mono', monospace;
          margin: 40px;
          text-align: center;
        }
      `}</style>
    </div>
  )
}

export default Layout
