import type { NextPage } from 'next'
import Head from 'next/head'

import Topbar from './topbar'

const Layout: NextPage = ({ children }) => {
  return (
    <div>
      <Head>
        <title>{process.env.test}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Topbar />

      <main>
        {children}
      </main>

      <footer className="footer">
        Copyright (c) 2021, Jisu Sim. All rights reserved.
      </footer>

      <style jsx>{`
        .footer {
          font-family: 'Consolas';
          margin: 40px;
          text-align: center;
        }
      `}</style>
    </div>
  )
}

export default Layout
